// Code generated by ent, DO NOT EDIT.

package passkey

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the passkey type in the database.
	Label = "passkey"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldOrigin holds the string denoting the origin field in the database.
	FieldOrigin = "origin"
	// FieldCrossOrigin holds the string denoting the cross_origin field in the database.
	FieldCrossOrigin = "cross_origin"
	// FieldTopOrigin holds the string denoting the top_origin field in the database.
	FieldTopOrigin = "top_origin"
	// FieldAttestationFmt holds the string denoting the attestation_fmt field in the database.
	FieldAttestationFmt = "attestation_fmt"
	// FieldBackupEligibilityBit holds the string denoting the backup_eligibility_bit field in the database.
	FieldBackupEligibilityBit = "backup_eligibility_bit"
	// FieldBackupStateBit holds the string denoting the backup_state_bit field in the database.
	FieldBackupStateBit = "backup_state_bit"
	// FieldSignCount holds the string denoting the sign_count field in the database.
	FieldSignCount = "sign_count"
	// FieldAaguid holds the string denoting the aaguid field in the database.
	FieldAaguid = "aaguid"
	// FieldCredentialID holds the string denoting the credential_id field in the database.
	FieldCredentialID = "credential_id"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldExtensionBit holds the string denoting the extension_bit field in the database.
	FieldExtensionBit = "extension_bit"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the passkey in the database.
	Table = "passkeys"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "passkeys"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for passkey fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldOrigin,
	FieldCrossOrigin,
	FieldTopOrigin,
	FieldAttestationFmt,
	FieldBackupEligibilityBit,
	FieldBackupStateBit,
	FieldSignCount,
	FieldAaguid,
	FieldCredentialID,
	FieldPublicKey,
	FieldExtensionBit,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// OriginValidator is a validator for the "origin" field. It is called by the builders before save.
	OriginValidator func(string) error
	// TopOriginValidator is a validator for the "top_origin" field. It is called by the builders before save.
	TopOriginValidator func(string) error
	// AaguidValidator is a validator for the "aaguid" field. It is called by the builders before save.
	AaguidValidator func([]byte) error
	// CredentialIDValidator is a validator for the "credential_id" field. It is called by the builders before save.
	CredentialIDValidator func([]byte) error
	// PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	PublicKeyValidator func([]byte) error
)

// AttestationFmt defines the type for the "attestation_fmt" enum field.
type AttestationFmt string

// AttestationFmt values.
const (
	AttestationFmtNone   AttestationFmt = "none"
	AttestationFmtPacked AttestationFmt = "packed"
	AttestationFmtTpm    AttestationFmt = "tpm"
)

func (af AttestationFmt) String() string {
	return string(af)
}

// AttestationFmtValidator is a validator for the "attestation_fmt" field enum values. It is called by the builders before save.
func AttestationFmtValidator(af AttestationFmt) error {
	switch af {
	case AttestationFmtNone, AttestationFmtPacked, AttestationFmtTpm:
		return nil
	default:
		return fmt.Errorf("passkey: invalid enum value for attestation_fmt field: %q", af)
	}
}

// OrderOption defines the ordering options for the Passkey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByOrigin orders the results by the origin field.
func ByOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrigin, opts...).ToFunc()
}

// ByCrossOrigin orders the results by the cross_origin field.
func ByCrossOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCrossOrigin, opts...).ToFunc()
}

// ByTopOrigin orders the results by the top_origin field.
func ByTopOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopOrigin, opts...).ToFunc()
}

// ByAttestationFmt orders the results by the attestation_fmt field.
func ByAttestationFmt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttestationFmt, opts...).ToFunc()
}

// ByBackupEligibilityBit orders the results by the backup_eligibility_bit field.
func ByBackupEligibilityBit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackupEligibilityBit, opts...).ToFunc()
}

// ByBackupStateBit orders the results by the backup_state_bit field.
func ByBackupStateBit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackupStateBit, opts...).ToFunc()
}

// BySignCount orders the results by the sign_count field.
func BySignCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignCount, opts...).ToFunc()
}

// ByExtensionBit orders the results by the extension_bit field.
func ByExtensionBit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtensionBit, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
