// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"mini-pasuki2/binid"
	"mini-pasuki2/ent/passkey"
	"mini-pasuki2/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Passkey is the model entity for the Passkey schema.
type Passkey struct {
	config `json:"-"`
	// ID of the ent.
	ID binid.BinId `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Origin holds the value of the "origin" field.
	Origin string `json:"origin,omitempty"`
	// AttestationFmt holds the value of the "attestation_fmt" field.
	AttestationFmt passkey.AttestationFmt `json:"attestation_fmt,omitempty"`
	// BackupEligibilityBit holds the value of the "backup_eligibility_bit" field.
	BackupEligibilityBit bool `json:"backup_eligibility_bit,omitempty"`
	// BackupStateBit holds the value of the "backup_state_bit" field.
	BackupStateBit bool `json:"backup_state_bit,omitempty"`
	// SignCount holds the value of the "sign_count" field.
	SignCount uint32 `json:"sign_count,omitempty"`
	// Aaguid holds the value of the "aaguid" field.
	Aaguid []byte `json:"aaguid,omitempty"`
	// CredentialID holds the value of the "credential_id" field.
	CredentialID []byte `json:"credential_id,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey []byte `json:"public_key,omitempty"`
	// ExtensionBit holds the value of the "extension_bit" field.
	ExtensionBit bool `json:"extension_bit,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID binid.BinId `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PasskeyQuery when eager-loading is set.
	Edges        PasskeyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PasskeyEdges holds the relations/edges for other nodes in the graph.
type PasskeyEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PasskeyEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Passkey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case passkey.FieldAaguid, passkey.FieldCredentialID, passkey.FieldPublicKey:
			values[i] = new([]byte)
		case passkey.FieldID, passkey.FieldUserID:
			values[i] = new(binid.BinId)
		case passkey.FieldBackupEligibilityBit, passkey.FieldBackupStateBit, passkey.FieldExtensionBit:
			values[i] = new(sql.NullBool)
		case passkey.FieldSignCount:
			values[i] = new(sql.NullInt64)
		case passkey.FieldOrigin, passkey.FieldAttestationFmt:
			values[i] = new(sql.NullString)
		case passkey.FieldCreatedAt, passkey.FieldUpdatedAt, passkey.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Passkey fields.
func (_m *Passkey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case passkey.FieldID:
			if value, ok := values[i].(*binid.BinId); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case passkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case passkey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case passkey.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case passkey.FieldOrigin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin", values[i])
			} else if value.Valid {
				_m.Origin = value.String
			}
		case passkey.FieldAttestationFmt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attestation_fmt", values[i])
			} else if value.Valid {
				_m.AttestationFmt = passkey.AttestationFmt(value.String)
			}
		case passkey.FieldBackupEligibilityBit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field backup_eligibility_bit", values[i])
			} else if value.Valid {
				_m.BackupEligibilityBit = value.Bool
			}
		case passkey.FieldBackupStateBit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field backup_state_bit", values[i])
			} else if value.Valid {
				_m.BackupStateBit = value.Bool
			}
		case passkey.FieldSignCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sign_count", values[i])
			} else if value.Valid {
				_m.SignCount = uint32(value.Int64)
			}
		case passkey.FieldAaguid:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field aaguid", values[i])
			} else if value != nil {
				_m.Aaguid = *value
			}
		case passkey.FieldCredentialID:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credential_id", values[i])
			} else if value != nil {
				_m.CredentialID = *value
			}
		case passkey.FieldPublicKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value != nil {
				_m.PublicKey = *value
			}
		case passkey.FieldExtensionBit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field extension_bit", values[i])
			} else if value.Valid {
				_m.ExtensionBit = value.Bool
			}
		case passkey.FieldUserID:
			if value, ok := values[i].(*binid.BinId); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Passkey.
// This includes values selected through modifiers, order, etc.
func (_m *Passkey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Passkey entity.
func (_m *Passkey) QueryUser() *UserQuery {
	return NewPasskeyClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Passkey.
// Note that you need to call Passkey.Unwrap() before calling this method if this Passkey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Passkey) Update() *PasskeyUpdateOne {
	return NewPasskeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Passkey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Passkey) Unwrap() *Passkey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Passkey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Passkey) String() string {
	var builder strings.Builder
	builder.WriteString("Passkey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("origin=")
	builder.WriteString(_m.Origin)
	builder.WriteString(", ")
	builder.WriteString("attestation_fmt=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttestationFmt))
	builder.WriteString(", ")
	builder.WriteString("backup_eligibility_bit=")
	builder.WriteString(fmt.Sprintf("%v", _m.BackupEligibilityBit))
	builder.WriteString(", ")
	builder.WriteString("backup_state_bit=")
	builder.WriteString(fmt.Sprintf("%v", _m.BackupStateBit))
	builder.WriteString(", ")
	builder.WriteString("sign_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SignCount))
	builder.WriteString(", ")
	builder.WriteString("aaguid=")
	builder.WriteString(fmt.Sprintf("%v", _m.Aaguid))
	builder.WriteString(", ")
	builder.WriteString("credential_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CredentialID))
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicKey))
	builder.WriteString(", ")
	builder.WriteString("extension_bit=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtensionBit))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// Passkeys is a parsable slice of Passkey.
type Passkeys []*Passkey
