// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mini-pasuki2/ent/passkey"
	"mini-pasuki2/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PasskeyUpdate is the builder for updating Passkey entities.
type PasskeyUpdate struct {
	config
	hooks    []Hook
	mutation *PasskeyMutation
}

// Where appends a list predicates to the PasskeyUpdate builder.
func (_u *PasskeyUpdate) Where(ps ...predicate.Passkey) *PasskeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasskeyUpdate) SetUpdatedAt(v time.Time) *PasskeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PasskeyUpdate) SetDeletedAt(v time.Time) *PasskeyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableDeletedAt(v *time.Time) *PasskeyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PasskeyUpdate) ClearDeletedAt() *PasskeyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetBackupEligibilityBit sets the "backup_eligibility_bit" field.
func (_u *PasskeyUpdate) SetBackupEligibilityBit(v bool) *PasskeyUpdate {
	_u.mutation.SetBackupEligibilityBit(v)
	return _u
}

// SetNillableBackupEligibilityBit sets the "backup_eligibility_bit" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableBackupEligibilityBit(v *bool) *PasskeyUpdate {
	if v != nil {
		_u.SetBackupEligibilityBit(*v)
	}
	return _u
}

// SetBackupStateBit sets the "backup_state_bit" field.
func (_u *PasskeyUpdate) SetBackupStateBit(v bool) *PasskeyUpdate {
	_u.mutation.SetBackupStateBit(v)
	return _u
}

// SetNillableBackupStateBit sets the "backup_state_bit" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableBackupStateBit(v *bool) *PasskeyUpdate {
	if v != nil {
		_u.SetBackupStateBit(*v)
	}
	return _u
}

// SetSignCount sets the "sign_count" field.
func (_u *PasskeyUpdate) SetSignCount(v uint32) *PasskeyUpdate {
	_u.mutation.ResetSignCount()
	_u.mutation.SetSignCount(v)
	return _u
}

// SetNillableSignCount sets the "sign_count" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableSignCount(v *uint32) *PasskeyUpdate {
	if v != nil {
		_u.SetSignCount(*v)
	}
	return _u
}

// AddSignCount adds value to the "sign_count" field.
func (_u *PasskeyUpdate) AddSignCount(v int32) *PasskeyUpdate {
	_u.mutation.AddSignCount(v)
	return _u
}

// SetExtensionBit sets the "extension_bit" field.
func (_u *PasskeyUpdate) SetExtensionBit(v bool) *PasskeyUpdate {
	_u.mutation.SetExtensionBit(v)
	return _u
}

// SetNillableExtensionBit sets the "extension_bit" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableExtensionBit(v *bool) *PasskeyUpdate {
	if v != nil {
		_u.SetExtensionBit(*v)
	}
	return _u
}

// Mutation returns the PasskeyMutation object of the builder.
func (_u *PasskeyUpdate) Mutation() *PasskeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PasskeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasskeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PasskeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasskeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasskeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasskeyUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Passkey.user"`)
	}
	return nil
}

func (_u *PasskeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkey.Table, passkey.Columns, sqlgraph.NewFieldSpec(passkey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(passkey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(passkey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BackupEligibilityBit(); ok {
		_spec.SetField(passkey.FieldBackupEligibilityBit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BackupStateBit(); ok {
		_spec.SetField(passkey.FieldBackupStateBit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SignCount(); ok {
		_spec.SetField(passkey.FieldSignCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSignCount(); ok {
		_spec.AddField(passkey.FieldSignCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.ExtensionBit(); ok {
		_spec.SetField(passkey.FieldExtensionBit, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PasskeyUpdateOne is the builder for updating a single Passkey entity.
type PasskeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasskeyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasskeyUpdateOne) SetUpdatedAt(v time.Time) *PasskeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PasskeyUpdateOne) SetDeletedAt(v time.Time) *PasskeyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableDeletedAt(v *time.Time) *PasskeyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PasskeyUpdateOne) ClearDeletedAt() *PasskeyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetBackupEligibilityBit sets the "backup_eligibility_bit" field.
func (_u *PasskeyUpdateOne) SetBackupEligibilityBit(v bool) *PasskeyUpdateOne {
	_u.mutation.SetBackupEligibilityBit(v)
	return _u
}

// SetNillableBackupEligibilityBit sets the "backup_eligibility_bit" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableBackupEligibilityBit(v *bool) *PasskeyUpdateOne {
	if v != nil {
		_u.SetBackupEligibilityBit(*v)
	}
	return _u
}

// SetBackupStateBit sets the "backup_state_bit" field.
func (_u *PasskeyUpdateOne) SetBackupStateBit(v bool) *PasskeyUpdateOne {
	_u.mutation.SetBackupStateBit(v)
	return _u
}

// SetNillableBackupStateBit sets the "backup_state_bit" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableBackupStateBit(v *bool) *PasskeyUpdateOne {
	if v != nil {
		_u.SetBackupStateBit(*v)
	}
	return _u
}

// SetSignCount sets the "sign_count" field.
func (_u *PasskeyUpdateOne) SetSignCount(v uint32) *PasskeyUpdateOne {
	_u.mutation.ResetSignCount()
	_u.mutation.SetSignCount(v)
	return _u
}

// SetNillableSignCount sets the "sign_count" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableSignCount(v *uint32) *PasskeyUpdateOne {
	if v != nil {
		_u.SetSignCount(*v)
	}
	return _u
}

// AddSignCount adds value to the "sign_count" field.
func (_u *PasskeyUpdateOne) AddSignCount(v int32) *PasskeyUpdateOne {
	_u.mutation.AddSignCount(v)
	return _u
}

// SetExtensionBit sets the "extension_bit" field.
func (_u *PasskeyUpdateOne) SetExtensionBit(v bool) *PasskeyUpdateOne {
	_u.mutation.SetExtensionBit(v)
	return _u
}

// SetNillableExtensionBit sets the "extension_bit" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableExtensionBit(v *bool) *PasskeyUpdateOne {
	if v != nil {
		_u.SetExtensionBit(*v)
	}
	return _u
}

// Mutation returns the PasskeyMutation object of the builder.
func (_u *PasskeyUpdateOne) Mutation() *PasskeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the PasskeyUpdate builder.
func (_u *PasskeyUpdateOne) Where(ps ...predicate.Passkey) *PasskeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PasskeyUpdateOne) Select(field string, fields ...string) *PasskeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Passkey entity.
func (_u *PasskeyUpdateOne) Save(ctx context.Context) (*Passkey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasskeyUpdateOne) SaveX(ctx context.Context) *Passkey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PasskeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasskeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasskeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasskeyUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Passkey.user"`)
	}
	return nil
}

func (_u *PasskeyUpdateOne) sqlSave(ctx context.Context) (_node *Passkey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkey.Table, passkey.Columns, sqlgraph.NewFieldSpec(passkey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Passkey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passkey.FieldID)
		for _, f := range fields {
			if !passkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != passkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(passkey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(passkey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BackupEligibilityBit(); ok {
		_spec.SetField(passkey.FieldBackupEligibilityBit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BackupStateBit(); ok {
		_spec.SetField(passkey.FieldBackupStateBit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SignCount(); ok {
		_spec.SetField(passkey.FieldSignCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSignCount(); ok {
		_spec.AddField(passkey.FieldSignCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.ExtensionBit(); ok {
		_spec.SetField(passkey.FieldExtensionBit, field.TypeBool, value)
	}
	_node = &Passkey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
