// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mini-pasuki2/ent/passkey"
	"mini-pasuki2/ent/schema"
	"mini-pasuki2/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	passkeyMixin := schema.Passkey{}.Mixin()
	passkeyMixinFields0 := passkeyMixin[0].Fields()
	_ = passkeyMixinFields0
	passkeyFields := schema.Passkey{}.Fields()
	_ = passkeyFields
	// passkeyDescCreatedAt is the schema descriptor for created_at field.
	passkeyDescCreatedAt := passkeyMixinFields0[0].Descriptor()
	// passkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	passkey.DefaultCreatedAt = passkeyDescCreatedAt.Default.(func() time.Time)
	// passkeyDescUpdatedAt is the schema descriptor for updated_at field.
	passkeyDescUpdatedAt := passkeyMixinFields0[1].Descriptor()
	// passkey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	passkey.DefaultUpdatedAt = passkeyDescUpdatedAt.Default.(func() time.Time)
	// passkey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	passkey.UpdateDefaultUpdatedAt = passkeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
