// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Passkey is the predicate function for passkey builders.
type Passkey func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
